export const FETCH_POKEMONS =  'FETCH_POKEMONS';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const POKEMON_SELECTED = 'POKEMON_SELECTED';
export const FETCH_EVOLUTION = 'FETCH_EVOLUTION';